stages:
  - infrastructure

build_infrastructure:
  stage: infrastructure
  image: hashicorp/terraform:light
  script:
    - cd infrastructure
    - terraform -version
    - terraform init
    - terraform plan