.infra_common: &infra_common
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - cd infrastructure

stages:
  - init
  - validate
  - plan
  - apply

init:
  stage: init
  <<: *infra_common
  script:
    - terraform --version
    - terraform init
  artifacts:
    expire_in: 1 day
    paths:
      - .terraform

validate:
  stage: validate
  <<: *infra_common
  script:
    - terraform validate
  dependencies:
    - init

plan:
  stage: plan
  <<: *infra_common
  script:
    - terraform plan -out "planfile"
    - ls -l
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile

apply:
  stage: apply
  <<: *infra_common
  script:
    - terraform apply -input=false "planfile"
  dependencies:
    - plan
  when: manual

# destroy:
#   stage: apply
#   <<: *infra_common
#   script:
#     - terraform destroy -input=false
#   dependencies:
#     - plan
#   when: manual