.infra_common: &infra_common
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' 
  before_script:
    - cd infrastructure
    - terraform --version
    - terraform init

stages:
  - validate
  - plan
  - apply

validate:
  stage: validate
  <<: *infra_common
  script:
    - terraform validate

plan:
  stage: plan
  <<: *infra_common
  dependencies:
    - validate
  script:
    - terraform plan -out "planfile"
    - ls -l
  artifacts:
    paths:
      - infrastructure/planfile

apply:
  stage: apply
  <<: *infra_common
  dependencies:
    - plan
  script:
    - terraform apply -input=false "planfile"
  when: manual

# destroy:
#   stage: apply
#   <<: *infra_common
#   script:
#     - terraform destroy -input=false
#   dependencies:
#     - plan
#   when: manual